import 'package:drift/drift.dart';
import 'animal.dart';
import 'behaviour_classification.dart';
import 'pastoralist.dart';

/// Alert type constants — must match the values stored in [DistressAlert.alertType]
abstract class AlertType {
  /// Animal spent less than the threshold hours grazing in a 24h window
  static const String lowFeeding = 'low_feeding';

  /// Animal spent less than the threshold hours ruminating in a 24h window
  static const String lowRumination = 'low_rumination';

  /// Animal spent more than the threshold hours walking in a 24h window
  /// Note: walking class is undertrained — use with caution until retrained
  static const String excessiveWalking = 'excessive_walking';
}

/// Severity level constants
abstract class AlertSeverity {
  /// Significant deviation from normal behavior — immediate attention needed
  static const String high = 'HIGH';

  /// Moderate deviation — monitor closely
  static const String medium = 'MEDIUM';
}

/// Generated by the alert pipeline when an animal's daily time budget
/// breaches a defined threshold across a 24-hour rolling window.
///
/// Created by: alert logic (behaviour module — you)
/// Consumed by: UI notification layer + Lynn's sync engine
///
/// Owned by: You (behaviour module)
class DistressAlert extends Table {
  TextColumn get id => text()();

  TextColumn get animalId =>
      text().references(Animal, #id)();

  /// The specific classification record that pushed the threshold over the limit
  TextColumn get classificationId =>
      text().references(BehaviourClassification, #id)();

  TextColumn get pastoralistId =>
      text().references(Pastoralist, #id)();

  /// One of AlertType constants: 'low_feeding', 'low_rumination', 'excessive_walking'
  TextColumn get alertType => text()();

  /// Human-readable alert message for display in the UI
  /// e.g. "Bessie has been grazing for only 2.1 hours in the last 24 hours"
  TextColumn get message => text()();

  /// One of AlertSeverity constants: 'HIGH' or 'MEDIUM'
  TextColumn get severity => text()();

  DateTimeColumn get timestamp => dateTime()();

  /// 0 = unread by pastoralist, 1 = acknowledged in the UI
  IntColumn get isAcknowledged =>
      integer().withDefault(const Constant(0))();

  /// 0 = pending upload to Firestore, 1 = synced
  /// Consumed by Lynn's sync engine
  IntColumn get synced => integer().withDefault(const Constant(0))();

  @override
  Set<Column> get primaryKey => {id};
}
